packaging_format = 2

id = "qbittorrent"
name = "qBittorrent"
description.en = "Bittorrent client that aims to be a good alternative to all other bittorrent clients."
description.fr = "Client bittorrent qui vise à être une bonne alternative à tous les autres clients bittorrent"

version = "5.1.4~ynh1"

maintainers = [""]

[upstream]
license = "GPL-3.0-or-later"
website = "https://www.qbittorrent.org"
admindoc = "https://github.com/qbittorrent/qBittorrent/wiki"
code = "https://github.com/qbittorrent/qBittorrent"
cpe = "cpe:2.3:a:qbittorrent:qbittorrent"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/"

[resources]

    [resources.sources]

        [resources.sources.main]
        amd64.url = "https://github.com/qbittorrent/qBittorrent/archive/9cd8544bf4d279a5ad3b6dd3a1c6d99e6aeb0d8d.tar.gz"
	    amd64.sha256 = "7481ca60e5421562dbad158b8aaf0a17295c49e06cb9361cb901aea067cc3136"

    [resources.system_user]
    allow_email = true
    
    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.protected = true
    main.allowed = "admins"
    api.url = "/api"
    api.allowed = "visitors"

    [resources.ports]

    [resources.apt]
    packages = [ 
        "libboost-dev",
        "libtorrent-rasterbar-dev",
        "libssl-dev",
        "zlib1g-dev",
        "cmake",
        "python3"
    ]